version: 1
backend:
  phases:
    build:
      commands:
        - cd web-ui
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: web-ui/build
    files:
      - '**/*'
  cache:
    paths:
      - web-ui/node_modules/**/*